name: contextx
description: Extensions on BuildContext for Flutter. It lets you replace calls like Navigator.of(context) with
  context.navigator().
version: 0.1.1
homepage: https://tonicartos.nz
repository: https://github.com/tonicartos/contextx
issue_tracker: https://github.com/tonicartos/contextx/issues


environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
